//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.0.0.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming



export interface AddProductsResponse {
    removedCount?: number;
    addedCount?: number;
    fileName?: string | undefined;
}

export interface ProductModel {
    providerCode?: string | undefined;
    barcode?: string | undefined;
    name?: string | undefined;
    description?: string | undefined;
    brandName?: string | undefined;
    retailPrice?: number | undefined;
}